 language: python

install: pip install -r requirements/requirements.txt
jobs:
  include:
  # --------------------------------------------
  - stage: test
    skip_cleanup: true
    script: 
      - make dev_env
      - make test
  # --------------------------------------------
  - stage: build+deploy:latest
    script: 
      - make dev_env
      - ./travis_scripts/deploy.sh
