language: python


jobs:
  include:
    # --------------------------------------------
  - stage: requirements
    skip_cleanup: true
    script: 
      - make dev_env
  # --------------------------------------------
  - stage: test
    skip_cleanup: true
    script: 
      - make test
  # --------------------------------------------
  - stage: build+push:latest

    deploy:
      provider: script
      script: ./travis_scripts/before_deploy.sh
    on:
      branch: sujay_sl5202