language: python
script: 
    - make dev_env
    - make test

jobs:
    include:
    - stage: test
        script:
        - make test
    
    - stage: build+push:latest
      
      before_deploy: 
        provider: script
        script: ./travis_scripts/before_deploy.sh

      on: 
        branch: sujay_sl5202