language: python
script: 
    - make dev_env
    - make test
    -echo "done"

before_deploy: 
    -cd travis_scripts
    script: bash before_deploy.sh

deploy: 
    -cd travis_scripts
    script: bash deploy.sh

after_deploy:
    cd travis_scripts
    script: bash after_deploy.sh